ui_config:
  default_summary_features:
    - actions: ["message_create", "message_delete", "message_update"]
      features: ["AuthorId", "AuthorName", "GuildId", "ChannelId", "MessageId"]
    - actions: ["message_create", "message_update"]
      features: ["Content"]
